rules {
  QUARANTINE {
    backend = "http";
    url = "http://mail-policy:9081/pipe";
    selector = "reject_no_global_bl";
    formatter = "multipart";
  }
	RLINFO {
		backend = "http";
		url = "http://mail-policy:9081/pipe_rl";
		selector = "ratelimited";
		formatter = "json";
	}
}

custom_select {
  ratelimited = <<EOD
return function(task)
  local ratelimited = task:get_symbol("RATELIMITED")
  if ratelimited then
    return true
  end
  return false
end
EOD;
  reject_no_global_bl = <<EOD
return function(task)
  if not task:has_symbol('GLOBAL_SMTP_FROM_BL')
    and not task:has_symbol('GLOBAL_MIME_FROM_BL')
    and not task:has_symbol('LOCAL_BL_ASN')
    and not task:has_symbol('GLOBAL_RCPT_BL')
    and not task:has_symbol('BAD_SUBJECT_00')
    and not task:has_symbol('MAILCOW_BLACK') then
      local action = task:get_metric_action('default')
      if action == 'reject' or action == 'add header' or action == 'rewrite subject' then
        return true
      end
  end
  return false
end
EOD;
}

custom_format {
  msgid = <<EOD
return function(task)
  return task:get_message_id()
end
EOD;
}

