# Uncomment below to apply the ratelimits globally. Use the platform ratelimit settings (Redis RL_VALUE) to overwrite them for a specific domain/mailbox.
# rates {
#     # Format: "1 / 1h" or "20 / 1m" etc.
#     to = "100 / 1s";
#     to_ip = "100 / 1s";
#     to_ip_from = "100 / 1s";
#     bounce_to = "100 / 1h";
#     bounce_to_ip = "7 / 1m";
# }