#!/bin/bash

trap "postfix stop" EXIT

[[ ! -d /opt/postfix/conf/sql/ ]] && mkdir -p /opt/postfix/conf/sql/

# Espera a PostgreSQL (rol mail_engine, sin contrasena: pg_isready solo comprueba el listener)
while ! pg_isready -q -h "${MAIL_DB_HOST}" -p "${MAIL_DB_PORT:-5432}" -U "${MAIL_DB_USER}" -d "${MAIL_DB_NAME}"; do
  echo "Waiting for database to come up..."
  sleep 2
done

until dig +short letsencrypt.org > /dev/null; do
  echo "Waiting for DNS..."
  sleep 1
done

cat <<EOF > /etc/aliases
# Autogenerated by Core Force Mail
null: /dev/null
watchdog: /dev/null
ham: "|/usr/local/bin/rspamd-pipe-ham"
spam: "|/usr/local/bin/rspamd-pipe-spam"
EOF
newaliases;

# create sni configuration
if [[ "${SKIP_LETS_ENCRYPT}" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
  echo -n "" > /opt/postfix/conf/sni.map
else
  echo -n "" > /opt/postfix/conf/sni.map;
  for cert_dir in /etc/ssl/mail/*/ ; do
    if [[ ! -f ${cert_dir}domains ]] || [[ ! -f ${cert_dir}cert.pem ]] || [[ ! -f ${cert_dir}key.pem ]]; then
      continue;
    fi
    IFS=" " read -r -a domains <<< "$(cat "${cert_dir}domains")"
    for domain in "${domains[@]}"; do
      echo -n "${domain} ${cert_dir}key.pem ${cert_dir}cert.pem" >> /opt/postfix/conf/sni.map;
      echo "" >> /opt/postfix/conf/sni.map;
    done
  done
fi
postmap -F hash:/opt/postfix/conf/sni.map;

# Cabecera comun de todos los mapas pgsql. Postfix escapa por si mismo los
# valores %s/%u/%d antes de interpolarlos en la consulta.
PGSQL_MAP_HEADER=$(cat <<EOF
# Autogenerated by Core Force Mail
hosts = ${MAIL_DB_HOST}:${MAIL_DB_PORT:-5432}
dbname = ${MAIL_DB_NAME}
user = ${MAIL_DB_USER}
password = ${MAIL_DB_PASSWORD}
EOF
)

cat <<EOF > /opt/postfix/conf/sql/pgsql_relay_ne.cf
${PGSQL_MAP_HEADER}
query = SELECT CASE WHEN EXISTS(SELECT address, domain FROM mail.aliases
      WHERE address = '%s'
        AND domain IN (
          SELECT domain FROM mail.domains
            WHERE backupmx
              AND relay_all_recipients
              AND relay_unknown_only)
      ) THEN 'lmtp:inet:dovecot:24' ELSE NULL END AS transport
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_relay_recipient_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT DISTINCT
  CASE WHEN '%d' IN (
    SELECT domain FROM mail.domains
      WHERE relay_all_recipients
        AND domain = '%d'
        AND backupmx
  )
  THEN '%s' ELSE (
    SELECT goto FROM mail.aliases WHERE address = '%s' AND active = 1
  )
  END AS result
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_tls_policy_override_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT policy || ' ' || parameters AS tls_policy FROM mail.tls_policy_overrides WHERE active AND dest = '%s'
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_tls_enforce_in_policy.cf
${PGSQL_MAP_HEADER}
query = SELECT CASE WHEN EXISTS(
  SELECT 'TLS_ACTIVE' FROM mail.aliases a
    LEFT OUTER JOIN mail.mailboxes m ON m.username = a.goto
      WHERE (a.address = '%s'
        OR a.address IN (
          SELECT '%u' || '@' || target_domain FROM mail.alias_domains
            WHERE alias_domain = '%d'
        )
      ) AND m.tls_enforce_in AND m.active = 1
  ) THEN 'reject_plaintext_session' ELSE NULL END AS tls_enforce_in
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_sender_dependent_default_transport_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT string_agg(transport, '' ORDER BY ord) AS transport_maps
  FROM (
    SELECT 1 AS ord, CASE WHEN EXISTS(SELECT 'smtp_type' FROM mail.aliases a
      LEFT OUTER JOIN mail.mailboxes m ON m.username = a.goto
        WHERE (a.address = '%s'
          OR a.address IN (
            SELECT '%u' || '@' || target_domain FROM mail.alias_domains
              WHERE alias_domain = '%d'
          )
        )
        AND m.tls_enforce_out
        AND m.active = 1
    ) THEN 'smtp_enforced_tls:' ELSE 'smtp:' END AS transport
    UNION ALL
    SELECT 2 AS ord, COALESCE(
      (SELECT r.hostname FROM mail.relayhosts r
      LEFT OUTER JOIN mail.mailboxes m ON m.relayhost_id = r.id
        WHERE r.active
          AND (
            m.username IN (SELECT a.goto FROM mail.aliases a
              JOIN mail.mailboxes mb ON mb.username = a.goto
                WHERE a.active = 1
                  AND a.address = '%s'
                  AND a.address NOT LIKE '@%%'
            )
          )
        LIMIT 1
      ),
      (SELECT r.hostname FROM mail.relayhosts r
      LEFT OUTER JOIN mail.domains d ON d.relayhost_id = r.id
        WHERE r.active
          AND (d.domain = '%d'
            OR d.domain IN (
              SELECT target_domain FROM mail.alias_domains
                WHERE alias_domain = '%d'
            )
          )
        LIMIT 1
      )
    ) AS transport
  ) AS transport_view
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_transport_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT 'smtp_via_transport_maps:' || nexthop AS transport FROM mail.transports
  WHERE active
  AND destination = '%s'
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_resource_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT 'null@localhost' FROM mail.mailboxes
  WHERE kind IN ('location', 'thing', 'group') AND username = '%s'
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_sasl_passwd_maps_sender_dependent.cf
${PGSQL_MAP_HEADER}
query = SELECT concat_ws(':', username, password) AS auth_data FROM mail.relayhosts
  WHERE id IN (
    SELECT COALESCE(
      (SELECT r.id FROM mail.relayhosts r
      LEFT OUTER JOIN mail.domains d ON d.relayhost_id = r.id
      WHERE r.active
        AND (d.domain = '%d'
          OR d.domain IN (
            SELECT target_domain FROM mail.alias_domains
            WHERE alias_domain = '%d'
          )
        )
      LIMIT 1
      ),
      (SELECT r.id FROM mail.relayhosts r
      LEFT OUTER JOIN mail.mailboxes m ON m.relayhost_id = r.id
      WHERE r.active
        AND (
          m.username IN (
            SELECT a.goto FROM mail.aliases a
              JOIN mail.mailboxes mb ON mb.username = a.goto
                WHERE a.active = 1
                  AND a.address = '%s'
                  AND a.address NOT LIKE '@%%'
          )
        )
      LIMIT 1
      )
    )
  )
  AND active
  AND username <> ''
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_sasl_passwd_maps_transport_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT concat_ws(':', username, password) AS auth_data FROM mail.transports
  WHERE nexthop = '%s'
  AND active
  AND username <> ''
  LIMIT 1
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_alias_domain_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT m.username FROM mail.mailboxes m, mail.alias_domains ad
  WHERE ad.alias_domain = '%d'
    AND m.username = '%u' || '@' || ad.target_domain
    AND m.active IN (1, 2)
    AND ad.active
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_alias_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT goto FROM mail.aliases
  WHERE address = '%s'
    AND active IN (1, 2)
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_recipient_canonical_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT new_dest FROM mail.recipient_maps
  WHERE old_dest = '%s'
    AND active
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_domains_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT alias_domain FROM mail.alias_domains WHERE alias_domain = '%s' AND active
  UNION
  SELECT domain FROM mail.domains
    WHERE domain = '%s'
      AND active
      AND NOT backupmx
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_mailbox_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT mailbox_format || path_prefix || '%d/%u/' FROM mail.mailboxes WHERE username = '%s' AND active IN (1, 2)
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_relay_domain_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT domain FROM mail.domains WHERE domain = '%s' AND backupmx AND active
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_sender_acl.cf
${PGSQL_MAP_HEADER}
# First select queries domain and alias_domain to determine if domains are active.
query = SELECT goto FROM mail.aliases
  WHERE id IN (
      SELECT COALESCE (
        (
          SELECT id FROM mail.aliases
            WHERE address = '%s'
            AND active IN (1, 2)
            AND sender_allowed
        ), (
          SELECT id FROM mail.aliases
            WHERE address = '@%d'
            AND active IN (1, 2)
            AND sender_allowed
        )
      )
    )
    AND active = 1
    AND sender_allowed
    AND (domain IN
      (SELECT domain FROM mail.domains
        WHERE domain = '%d'
          AND active)
      OR domain IN (
        SELECT alias_domain FROM mail.alias_domains
          WHERE alias_domain = '%d'
            AND active
      )
    )
  UNION
  SELECT logged_in_as FROM mail.sender_acl
    WHERE send_as = '@%d'
      OR send_as = '%s'
      OR send_as = '*'
      OR send_as IN (
        SELECT '@' || target_domain FROM mail.alias_domains
          WHERE alias_domain = '%d')
      OR send_as IN (
        SELECT '%u' || '@' || target_domain FROM mail.alias_domains
          WHERE alias_domain = '%d')
      AND logged_in_as NOT IN (
        SELECT goto FROM mail.aliases
          WHERE address = '%s')
  UNION
  SELECT m.username FROM mail.mailboxes m, mail.alias_domains ad
    WHERE ad.alias_domain = '%d'
      AND m.username = '%u' || '@' || ad.target_domain
      AND m.active IN (1, 2)
      AND ad.active
EOF

# MX based routing
cat <<EOF > /opt/postfix/conf/sql/pgsql_mbr_access_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT 'FILTER smtp_via_transport_maps:' || nexthop AS transport FROM mail.transports
  WHERE '%s' ~ destination
    AND active
    AND is_mx_based
EOF

cat <<EOF > /opt/postfix/conf/sql/pgsql_virtual_spamalias_maps.cf
${PGSQL_MAP_HEADER}
query = SELECT goto FROM mail.spam_aliases
  WHERE address = '%s'
    AND (valid_until >= now() OR permanent)
EOF

if [ ! -f /opt/postfix/conf/dns_blocklists.cf ]; then
  cat <<EOF > /opt/postfix/conf/dns_blocklists.cf
# This file can be edited.
# Delete this file and restart postfix container to revert any changes.
postscreen_dnsbl_sites = wl.mailspike.net=127.0.0.[18;19;20]*-2
  hostkarma.junkemailfilter.com=127.0.0.1*-2
  list.dnswl.org=127.0.[0..255].0*-2
  list.dnswl.org=127.0.[0..255].1*-4
  list.dnswl.org=127.0.[0..255].2*-6
  list.dnswl.org=127.0.[0..255].3*-8
  bl.spamcop.net*2
  bl.suomispam.net*2
  hostkarma.junkemailfilter.com=127.0.0.2*3
  hostkarma.junkemailfilter.com=127.0.0.4*2
  hostkarma.junkemailfilter.com=127.0.1.2*1
  backscatter.spameatingmonkey.net*2
  bl.ipv6.spameatingmonkey.net*2
  bl.spameatingmonkey.net*2
  b.barracudacentral.org=127.0.0.2*7
  bl.mailspike.net=127.0.0.2*5
  bl.mailspike.net=127.0.0.[10;11;12]*4
EOF
fi

# Remove discontinued DNSBLs from existing dns_blocklists.cf
sed -i '/ix\.dnsbl\.manitu\.net\*2/d' /opt/postfix/conf/dns_blocklists.cf # Nixspam

DNSBL_CONFIG=$(grep -v '^#' /opt/postfix/conf/dns_blocklists.cf | grep '\S')

if [ ! -z "$DNSBL_CONFIG" ]; then
  if [ -n "$SPAMHAUS_DQS_KEY" ]; then
    echo -e "\e[32mDetected SPAMHAUS_DQS_KEY variable from .env...\e[0m"
    echo -e "\e[33mUsing DQS Blocklists from Spamhaus!\e[0m"
    SPAMHAUS_DNSBL_CONFIG=$(cat <<EOF
  ${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.net=127.0.0.[4..7]*6
  ${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.net=127.0.0.[10;11]*8
  ${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.net=127.0.0.3*4
  ${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.net=127.0.0.2*3
postscreen_dnsbl_reply_map = texthash:/opt/postfix/conf/dnsbl_reply.map
EOF

  cat <<EOF > /opt/postfix/conf/dnsbl_reply.map
# Autogenerated by Core Force Mail, using Spamhaus DQS reply domains
${SPAMHAUS_DQS_KEY}.sbl.dq.spamhaus.net     sbl.spamhaus.org
${SPAMHAUS_DQS_KEY}.xbl.dq.spamhaus.net     xbl.spamhaus.org
${SPAMHAUS_DQS_KEY}.pbl.dq.spamhaus.net     pbl.spamhaus.org
${SPAMHAUS_DQS_KEY}.zen.dq.spamhaus.net     zen.spamhaus.org
${SPAMHAUS_DQS_KEY}.dbl.dq.spamhaus.net     dbl.spamhaus.org
${SPAMHAUS_DQS_KEY}.zrd.dq.spamhaus.net     zrd.spamhaus.org
EOF
    )
  else
    if [ -f "/opt/postfix/conf/dnsbl_reply.map" ]; then
      rm /opt/postfix/conf/dnsbl_reply.map
    fi
    # Las listas abiertas de Spamhaus rechazan consultas desde AS "malos" y desde
    # resolvers publicos. Solo se activan si un servicio externo (SPAMHAUS_ASN_CHECK_URL)
    # confirma que el AS de esta IP no esta vetado; sin esa URL se desactivan por seguridad.
    if [ -n "${SPAMHAUS_ASN_CHECK_URL}" ]; then
      echo -e "\e[33mChecking if ASN for your IP is listed for Spamhaus Bad ASN List...\e[0m"
      response=$(curl --connect-timeout 15 --max-time 30 -s -o /dev/null -w "%{http_code}" "${SPAMHAUS_ASN_CHECK_URL}")
    else
      response=0
    fi
    if [ "$response" -eq 503 ]; then
      echo -e "\e[31mThe AS of your IP is listed as a banned AS from Spamhaus!\e[0m"
      echo -e "\e[33mNo SPAMHAUS_DQS_KEY found... Skipping Spamhaus blocklists entirely!\e[0m"
      SPAMHAUS_DNSBL_CONFIG=""
    elif [ "$response" -eq 200 ]; then
      echo -e "\e[32mThe AS of your IP is NOT listed as a banned AS from Spamhaus!\e[0m"
      echo -e "\e[33mUsing the open Spamhaus blocklists.\e[0m"
      SPAMHAUS_DNSBL_CONFIG=$(cat <<EOF
  zen.spamhaus.org=127.0.0.[10;11]*8
  zen.spamhaus.org=127.0.0.[4..7]*6
  zen.spamhaus.org=127.0.0.3*4
  zen.spamhaus.org=127.0.0.2*3
EOF
      )

    else
      echo -e "\e[31mCould not determine the AS of this IP (SPAMHAUS_ASN_CHECK_URL unset, DNS or network issue). Response Code: $response\e[0m"
      echo -e "\e[33mDeactivating Spamhaus DNS Blocklists to be on the safe side!\e[0m"
      SPAMHAUS_DNSBL_CONFIG=""
    fi
  fi
fi

# Reset main.cf
sed -i '/Overrides/q' /opt/postfix/conf/main.cf
echo >> /opt/postfix/conf/main.cf
# Append postscreen dnsbl sites to main.cf
if [ ! -z "$DNSBL_CONFIG" ]; then
  echo -e "${DNSBL_CONFIG}\n${SPAMHAUS_DNSBL_CONFIG}" >> /opt/postfix/conf/main.cf
fi
# Append user overrides
echo -e "\n# User Overrides" >> /opt/postfix/conf/main.cf
touch /opt/postfix/conf/extra.cf
sed -i '/\$myhostname/! { /myhostname/d }' /opt/postfix/conf/extra.cf
echo -e "myhostname = ${MAIL_HOSTNAME}\n$(cat /opt/postfix/conf/extra.cf)" > /opt/postfix/conf/extra.cf
cat /opt/postfix/conf/extra.cf >> /opt/postfix/conf/main.cf

if [ ! -f /opt/postfix/conf/custom_transport.pcre ]; then
  echo "Creating dummy custom_transport.pcre"
  touch /opt/postfix/conf/custom_transport.pcre
fi

if [[ ! -f /opt/postfix/conf/custom_postscreen_whitelist.cidr ]]; then
  echo "Creating dummy custom_postscreen_whitelist.cidr"
  cat <<EOF > /opt/postfix/conf/custom_postscreen_whitelist.cidr
# Autogenerated by Core Force Mail
# Rules are evaluated in the order as specified.
# Blacklist 192.168.* except 192.168.0.1.
# 192.168.0.1          permit
# 192.168.0.0/16       reject
EOF
fi

# Fix Postfix permissions
chown -R root:postfix /opt/postfix/conf/sql/ /opt/postfix/conf/custom_transport.pcre
chmod 640 /opt/postfix/conf/sql/*.cf /opt/postfix/conf/custom_transport.pcre
chgrp -R postdrop /var/spool/postfix/public
chgrp -R postdrop /var/spool/postfix/maildrop
postfix set-permissions

# Checking if there is a leftover of a crashed postfix container before starting a new one
if [ -e /var/spool/postfix/pid/master.pid ]; then
  rm -rf /var/spool/postfix/pid/master.pid
fi

# Check Postfix configuration
postconf -c /opt/postfix/conf > /dev/null

if [[ $? != 0 ]]; then
  echo "Postfix configuration error, refusing to start."
  exit 1
else
  postfix -c /opt/postfix/conf start
  sleep 126144000
fi
